#=================================================================
# 对象存储配置
#=================================================================
storage:
  minio:
    endpoint: http://127.0.0.1:9000
    domain: http://116.62.199.48:9001
    accessKey: quanxiaoha
    secretKey: quanxiaoha
  aliyun-oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    accessKey: LTAI5t9QvhLe4XUEmndxEVCk
    secretKey: I2gwUkjPlIc3ZGYpTMan8yqlAJmvtS

